[package]
name = "badger"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = "0.11.7"
futures = "0.3.31"
pretty_env_logger = "0.5.0"
rand = "0.8.5"
tokio = { version = "1.42.0", features = ["full"] }
uuid = "1.11.0"
